### ISSUE TITLE
[Suggestion] Add Masked Carnivale Instances

### ISSUE THREAD

**Issue by Rellawing** [Tischel/NOTED#3]
Would you mind adding the Blue Mage Masked Carnivale? I'd like to make notes with your mod, but I can't. I have to use the other bulkier one because going through all the list of dungeons, etc... I couldn't find anything under Masked or Blue or Carnivale.

Thank you!

**Comment by Tischel** [comment]
Each separated challenge was actually present in the duty list (i.e "All's Well That Starts Well", "Much Ado About Pudding", etc).
However since all of them actually happen inside the same place, the internal identifier of this duties was duplicated.
I noticed this was causing issues.

I removed these from the duty list, and added a new "The Masked Carnivale" entry.
You should be able to create all the notes you want in that single duty and then swap notes for each challenge.

Added in v1.1.1.0

**Comment by Rellawing** [comment]
That would be a great deal less confusing! Thank you very much!
